### ISSUE TITLE
Error in calculation of minimal bbox tile

### ISSUE THREAD

**Issue by nesterenko-kv** [bertt/tilebelt-cs#1]
BBox: [-180, 41.1850968, 180, 82.0586232]
Expected tile: (0, 0, 0)
Actual: (0, 0, 1)

**Comment by bertt** [comment]
Hi, I've tested this on MapBox Tilebelt library, it gives also 0,0,1

**Comment by nesterenko-kv** [comment]
That's not correct, cuz it covers more than one tile
![image](https://user-images.githubusercontent.com/10574210/70990319-f3452180-20cd-11ea-875e-1443cf68c0a4.png)

**Comment by bertt** [comment]
yeah I see, I suspect something in method GetBBoxZoom needs some attention https://github.com/bertt/tilebelt-cs/blob/master/tilebelt-cs/Tilebelt.cs#L42

**Comment by bertt** [comment]
fixed in https://github.com/bertt/tilebelt-cs/commit/55558e41e31322c5fba4e051990f41dcda13541e , published in release 1.3.4

**Comment by nesterenko-kv** [comment]
Thanks!
